import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { AccessibilityIssue } from '@/lib/claude';
import { WCAGPrinciple } from '@/visualization/types';
import { buildDeveloperHandoffMarkdown } from '@/lib/report';

export async function POST(req: NextRequest) {
  const { issues, principle, url, pageTitle }: {
    issues: AccessibilityIssue[];
    principle: WCAGPrinciple;
    url: string;
    pageTitle: string;
  } = await req.json();

  const baseMarkdown = buildDeveloperHandoffMarkdown(issues, url, pageTitle);

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ markdown: baseMarkdown });
  }

  const ai = new GoogleGenAI({ apiKey });
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const principleDescriptions: Record<WCAGPrinciple, string> = {
    Perceivable: 'content must be presentable to users in ways they can perceive (alt text, contrast, captions, audio descriptions)',
    Operable: 'UI components and navigation must be operable (keyboard access, focus management, click targets, no keyboard traps)',
    Understandable: 'information and operation of UI must be understandable (language, labels, error messages, predictable behavior)',
    Robust: 'content must be robust enough to be interpreted by assistive technologies (valid ARIA, semantic HTML, parsing)',
  };

  const issuesJson = JSON.stringify(
    issues.map(i => ({
      severity: i.severity,
      title: i.title,
      wcag: i.wcag,
      description: i.description,
      fix: i.fix,
      selector: i.selector,
      element: i.element,
    })),
    null,
    2
  );

  const prompt = `You are a senior accessibility engineer writing a developer handoff document for a development team.

Page: ${pageTitle || url}
URL: ${url}
Scan Date: ${dateStr}
WCAG Principle: ${principle}
Principle Summary: ${principleDescriptions[principle]}

Issues found (JSON):
${issuesJson}

Write a developer handoff markdown document. Use this exact structure:

# Developer Handoff: ${principle} Issues
**Page:** [${pageTitle || url}](${url})
**Principle:** ${principle} — ${principleDescriptions[principle]}
**Scanned:** ${dateStr}

---

## What is "${principle}"?
[2-3 sentence explanation of this WCAG principle and why it matters for real users]

---

## Issues (${issues.filter(i => i.severity !== 'Pass').length} to fix)

[For each Critical/Warning issue, use this format:]

### [NUMBER]. [SEVERITY EMOJI] [TITLE]
> **WCAG:** [criterion] | **Severity:** [severity]

**Problem:** [description]

**Fix:**
[specific actionable fix — if there's a code change needed, show it in a code block]

**Target:** \`[selector]\`

---

## Quick Wins
[Bullet list of the 2-3 easiest/fastest fixes — items that can be done in under 10 minutes]

## Testing Checklist
[Markdown checklist with - [ ] items for verifying each fix is working]

---

*Generated by a11y.sense (https://github.com/a11y.sense) · ${dateStr}*

Rules:
- Be specific and actionable — no vague recommendations
- Use ✅ for Pass, ⚠️ for Warning, 🚨 for Critical in headings
- Keep code snippets minimal and correct
- Output ONLY the markdown document, no preamble`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      config: { temperature: 0.3 },
    });
    const markdown = response.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? baseMarkdown;
    return NextResponse.json({ markdown });
  } catch (err) {
    console.error('[Handoff] Gemini error:', err);
    return NextResponse.json({ markdown: baseMarkdown });
  }
}
